project: https://github.com/AudioReach/audioreach-engine

branches:
  master:
    modes:
      blocking:
        headers:
          - fwk/api/apm/*.h
          - fwk/api/ar_utils/*.h
          - fwk/api/modules/*.h
          - fwk/api/vcpm/*.h
          - fwk/spf/dls/api/*.h
